// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using U2D_RPG_Demo.ApiServer.Models;

#nullable disable

namespace U2D_RPG_Demo.ApiServer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240708025605_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("U2D_RPG_Demo.ApiServer.Models.PlayerAttributes", b =>
                {
                    b.Property<int>("PAID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PAID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PAID"));

                    b.Property<double?>("ATK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(5.0)
                        .HasColumnName("ATK");

                    b.Property<double?>("DEF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(2.0)
                        .HasColumnName("DEF");

                    b.Property<double?>("DR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.10000000000000001)
                        .HasColumnName("DR");

                    b.Property<int?>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<double?>("Hp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(100.0)
                        .HasColumnName("HP");

                    b.Property<int?>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<double?>("MaxHp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(100.0)
                        .HasColumnName("MaxHP");

                    b.Property<double?>("MaxMp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(100.0)
                        .HasColumnName("MaxMP");

                    b.Property<double?>("Mp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(100.0)
                        .HasColumnName("MP");

                    b.Property<double?>("SPD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(5.0)
                        .HasColumnName("SPD");

                    b.Property<double?>("SPDMult")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0)
                        .HasColumnName("SPD_MULT");

                    b.Property<int>("UID")
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    b.HasKey("PAID")
                        .HasName("PK__PlayerAt__5986FD6D38FACDC1");

                    b.HasIndex("UID");

                    b.ToTable("PlayerAttributes");
                });

            modelBuilder.Entity("U2D_RPG_Demo.ApiServer.Models.UserInfo", b =>
                {
                    b.Property<int>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UID"));

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("HasDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("LastUpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)")
                        .HasDefaultValue("nobody");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Aa123456");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("UID")
                        .HasName("PK__UserInfo__C5B196020D417FD6");

                    b.ToTable("UserInfo", (string)null);
                });

            modelBuilder.Entity("U2D_RPG_Demo.ApiServer.Models.PlayerAttributes", b =>
                {
                    b.HasOne("U2D_RPG_Demo.ApiServer.Models.UserInfo", "UidNavigation")
                        .WithMany("PlayerAttributes")
                        .HasForeignKey("UID")
                        .IsRequired()
                        .HasConstraintName("FK__PlayerAttri__UID__09A971A2");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("U2D_RPG_Demo.ApiServer.Models.UserInfo", b =>
                {
                    b.Navigation("PlayerAttributes");
                });
#pragma warning restore 612, 618
        }
    }
}
